
DROP TABLE IF EXISTS USERS, TASKS;


CREATE TABLE IF NOT EXISTS USERS
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id       BIGINT        NOT NULL UNIQUE,
    first_name        VARCHAR(2500) NOT NULL,
    last_name         VARCHAR(2500),
    personal_number   INTEGER,
    registration_date TIMESTAMP WITHOUT TIME ZONE,
    manager_id        BIGINT,
    is_manager        BOOLEAN,
    division          VARCHAR,
    worker_id         BIGINT,
    tittle_for_task   VARCHAR,
    end_of_task       TIMESTAMP WITHOUT TIME ZONE,
    task_text         VARCHAR,
    task_score        INTEGER
);

CREATE TABLE IF NOT EXISTS TASKS
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_id BIGINT,
    worker_id  BIGINT,
    tittle     VARCHAR,
    text       VARCHAR,
    score      INTEGER,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    status     VARCHAR
);



