DROP TABLE IF EXISTS USERS;

CREATE TABLE IF NOT EXISTS USERS
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id       BIGINT        NOT NULL UNIQUE,
    first_name        VARCHAR(2500) NOT NULL,
    last_name         VARCHAR(2500),
    personal_number   INTEGER,
    registration_date TIMESTAMP WITHOUT TIME ZONE,
    manager_id        BIGINT,
    is_manager        BOOLEAN,
    division          VARCHAR
);

CREATE TABLE IF NOT EXISTS TASKS
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_id BIGINT,
    worker_id  BIGINT,
    text       VARCHAR,
    score      INTEGER,
    start_date TIMESTAMP WITHOUT TIME ZONE,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    is_done    BOOLEAN,
    is_agreed  BOOLEAN
);



