/*DROP TABLE IF EXISTS USERS, TASKS, PICTURES;*/


CREATE TABLE IF NOT EXISTS USERS
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    telegram_id       BIGINT UNIQUE,
    first_name        VARCHAR(2500),
    last_name         VARCHAR(2500),
    personal_number   INTEGER,
    registration_date TIMESTAMP WITHOUT TIME ZONE,
    manager_id        BIGINT,
    is_manager        BOOLEAN,
    division          VARCHAR,
    worker_id         BIGINT,
    tittle_for_task   VARCHAR,
    end_of_task       TIMESTAMP WITHOUT TIME ZONE,
    task_text         VARCHAR,
    task_score        INTEGER,
    status            VARCHAR,
    position          VARCHAR,
    rating            BIGINT
);

CREATE TABLE IF NOT EXISTS TASKS
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    manager_id  BIGINT,
    worker_id   BIGINT,
    tittle      VARCHAR,
    text        VARCHAR,
    score       INTEGER,
    start_date  TIMESTAMP WITHOUT TIME ZONE,
    end_date    TIMESTAMP WITHOUT TIME ZONE,
    task_status VARCHAR,
    is_repeat   BOOLEAN,
    period      INTEGER
);

CREATE TABLE IF NOT EXISTS PICTURES
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    add_date TIMESTAMP WITHOUT TIME ZONE,
    tittle   VARCHAR,
    link     VARCHAR,
    actual   BOOLEAN
);



